export const constans = {
  API_URL: 'http://nerdistry.pl:3000/api/all',
  STATIONS_API_URL: 'http://nerdistry.pl:3000/api/getIndex/',
};

export const links = {
  GITHUB: 'https://github.com/DarekMazur',
};

export const language = {
  EN: {
    langName: 'english',
    langShortName: 'en',
    appTitle: 'SmoggyFoggy',
    so2: 'Sulphur dioxide',
    no2: 'Nitrogen dioxide',
    o3: 'Ozone',
    pm25: 'Atmospheric aerosols (PM2.5)',
    pm10: 'Suspended dust (PM10)',
    sationHeader: 'Measuring station',
    stationTime: 'Measuring time',
    statusTitle: 'Quality',
    noData: 'No data',
    status0: 'Very good',
    status1: 'Good',
    status2: 'Moderate',
    status3: 'Sufficient',
    status4: 'Bad',
    status5: 'Very bad',
    formTitle: 'or choose station from list',
    loader: 'Loading...',
    province: 'Choose province:',
    city: 'Choose city:',
    station: 'Choose station:',
    geoButton: 'Find closest station',
    err: 'Something goes wrong... please check your Internet connection',
    geoOff:
      "Can't get your location. Please check device setup and turn geolocation on or choose station manually.",
    reset: 'RESET',
  },
  PL: {
    langName: 'polski',
    langShortName: 'pl',
    appTitle: 'SmoggyFoggy',
    so2: 'Dwutlenek siarki',
    no2: 'Dwutlenek azotu',
    o3: 'Ozon',
    pm25: 'Aerozole atmosferyczne (PM2.5)',
    pm10: 'Pył zawieszony (PM10)',
    sationHeader: 'Stacja pomiarowa',
    stationTime: 'Data pomiaru',
    statusTitle: 'Jakość',
    noData: 'Brak danych',
    status0: 'Bardzo dobry',
    status1: 'Dobry',
    status2: 'Umiarkowany',
    status3: 'Dostateczny',
    status4: 'Zły',
    status5: 'Bardzo zły',
    formTitle: 'lub wybierz stację z listy',
    loader: 'Pobieranie danych...',
    province: 'Wybierz region:',
    city: 'Wybierz miasto:',
    station: 'Wybierz stację:',
    geoButton: 'Znajdź najbliższą stację',
    err: 'Coś poszło nie tak... sprawdź połączenie z internetem...',
    geoOff:
      'Nie można odczytać Twojej lokalizacji. Sprawdź konfigurację urządzenia i włącz geolokalizację lub wybierz stację ręcznie.',
    reset: 'WYCZYŚĆ',
  },
  RU: {
    langName: 'русский',
    langShortName: 'ru',
    appTitle: 'SmoggyFoggy',
    so2: 'Двутленек сиарки',
    no2: 'Диоксид азота',
    o3: 'Озон',
    pm25: 'Атмосферные аэрозоли (PM2.5)',
    pm10: 'Взвешенная пыль (PM10)',
    sationHeader: 'Измерительная станция',
    stationTime: 'Время измерения',
    statusTitle: 'Качество',
    noData: 'Нет данных',
    status0: 'Очень хороший',
    status1: 'Хороший',
    status2: 'Умеренный',
    status3: 'Достаточный',
    status4: 'Плохой',
    status5: 'Очень плохой',
    formTitle: 'или выберите станцию ​​из списка',
    loader: 'Загрузка...',
    province: 'Выберите провинцию:',
    city: 'Выберите город:',
    station: 'Выберите станцию:',
    geoButton: 'Найти ближайшую станцию',
    err: 'Что-то пошло не так ... Пожалуйста, проверьте подключение к интернету',
    geoOff:
      'Не могу определить ваше местоположение. Проверьте настройки устройства и включите геолокацию или выберите станцию ​​вручную.',
    reset: 'ЧИСТЫЙ',
  },
};
