export const constans = {
  PROXY: 'https://thingproxy.freeboard.io/fetch/',
  // PROXY: 'https://cors-anywhere-gacek.herokuapp.com/',
  API_URL: 'https://air-condition-cors-proxy.herokuapp.com/station/findAll',
  STATIONS_API_URL: 'https://air-condition-cors-proxy.herokuapp.com/aqindex/getIndex/',
  HEADERS: {},
};

export const language = {
  EN: {
    langName: 'english',
    langShortName: 'en',
    appTitle: 'Air quality',
    so2: 'Sulphur dioxide',
    no2: 'Nitrogen dioxide',
    o3: 'Ozone',
    pm25: 'Atmospheric aerosols (PM2.5)',
    pm10: 'Suspended dust (PM10)',
    sationHeader: 'Measuring station',
    stationTime: 'Measuring time',
    noData: 'No data',
    status0: 'Very good',
    status1: 'Good',
    status2: 'Moderate',
    status3: 'Sufficient',
    status4: 'Bad',
    status5: 'Very bad',
    formTitle: 'or choose station from list',
    loader: 'Loading...',
    province: 'Choose province:',
    city: 'Choose city:',
    station: 'Choose station:',
    geoButton: 'Find closest station',
    err: 'Something goes wrong... please try again',
  },
  PL: {
    langName: 'polski',
    langShortName: 'pl',
    appTitle: 'Jakość powietrza',
    so2: 'Dwutlenek siarki',
    no2: 'Dwutlenek azotu',
    o3: 'Ozon',
    pm25: 'Aerozole atmosferyczne (PM2.5)',
    pm10: 'Pył zawieszony (PM10)',
    sationHeader: 'Stacja pomiarowa',
    stationTime: 'Data pomiaru',
    noData: 'Brak danych',
    status0: 'Bardzo dobry',
    status1: 'Dobry',
    status2: 'Umiarkowany',
    status3: 'Dostateczny',
    status4: 'Zły',
    status5: 'Bardzo zły',
    formTitle: 'lub wybierz stację z listy',
    loader: 'Pobieranie danych...',
    province: 'Wybierz region:',
    city: 'Wybierz miasto:',
    station: 'Wybierz stację:',
    geoButton: 'Znajdź najbliższą stację',
    err: 'Coś poszło nie tak... spróbuj ponownie później...',
  },
};
